### ISSUE TITLE
Uncommited lock file

### ISSUE THREAD

**Issue by Udiknedormin** [ppierzchalka/vue-training#2]
After `npm install`, I get package-lock.json created and unknown to git. It also yield info from npm:
```
npm notice created a lockfile as package-lock.json. You should commit this file.
```
Lockfile as package-lock.json is uncommited on [list-task](https://github.com/ppierzchalka/vue-training/tree/list-task) branch, commit [2b001c6](https://github.com/ppierzchalka/vue-training/commit/2b001c6c84e32d45acdbc4225535f8e7025489b0).

Because lockfile isn't commited, different versions of packages can be downloaded by different users of this repo, which can make it difficult to track bugs in configuration.

**Comment by ppierzchalka** [comment]
I've used yarn and yarn.lock file is commited to the repo.

**Comment by Udiknedormin** [comment]
Ok, closing.
